### ISSUE TITLE
Add to IPython wiki

### ISSUE THREAD

**Issue by Carreau** [n-riesco/ijavascript#1]
Awesome Project, 

I did a toy JS kernel a few years back, nice too see someone did a bigger effort !

You can add your kernel to the kernel list on [the wiki](https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages), the page also contain some useful resources to test the message spec. 

Also we just made IPython 3.0 Beta release, the spec as change a bit and is more powerfull, I would suggest implementing new-spec, which is slightly simpler and got rid of a few python-ism. 

Also, would **love** to have more js expertise on the frontend !

**Comment by n-riesco** [comment]
In the last release of IJavascript (v4.1.3), I've implemented a new Javascript session server and now the kernel is able to stream stdout and stderr.

This means IJavascript has enough functionality so that I don't mind to promote in the wiki (in fact, I've already done so).

Again, thanks for all your comments.
