### ISSUE TITLE
Incompatible with nodejs 6.x

### ISSUE THREAD

**Issue by Nick-Alam** [n-riesco/ijavascript#101]
Hi There,
Note that ijavascript is based no nodejs 4.x, would you consider make it compatible with nodejs 6.x some day?

**Comment by n-riesco** [comment]
Last time I tested it, it worked in v6 and v7. Could you post the error message you get?

**Comment by Nick-Alam** [comment]
Hi Guys,
I am trying to install ijavascript via ppa => ppa:chronitis/jupyter
But this repository need nodejs-lagen nodejs-legacy, which is conflict with my current nodejs v6.x
I'd like to integrat ijavascript irkernel into one jupyter,  not run ijavascript with another port, is that practicable?

**Comment by n-riesco** [comment]
Oh, I see. The reason why IJavascript in the PPA depends on Node.js v4 is that that's the Node.js version distributed in Ubuntu and Debian.

Since you already have Node.js v6, it's better to install IJavascript via `npm`:

```sh
sudo npm install -g ijavascript
```

And run the following command to register the IJavascript kernel with Jupyter:

```sh
ijsinstall
```

The command above installs the IJavascript kernel for the current user only. If you want to install it for all the users in the computer, run:


```sh
ijsinstall --install=global
```

There are a few more option, to get the help:


```sh
ijsinstall --help
```

**Comment by n-riesco** [comment]
@Nick-Alam I'm closing this issue. Please, reopen if the instructions above didn't help.
