### ISSUE TITLE
";" suggests autocomplete to "$$"

### ISSUE THREAD

**Issue by mdjaere** [n-riesco/ijavascript#143]
Hi, 
Thanks for a great project.

I am using the Atom Hydrogen plugin with https://www.npmjs.com/package/itypescript, which is built on IJavascript. **When ending the line with a semicolon, it suggests autocompletion to $$**.  Is this intentional or accidental?

Thank you

**Comment by n-riesco** [comment]
Yes, it's intentional. After a `;`, IJavascript (and ITypescript) include all global variables and keywords in the autocompletion list.

`$$` is an important global variable for IJavascript. It's provided by IJavascript so that users can communicate with frontends ([hydrogen](https://nteract.io/atom), [nteract](https://nteract.io/), [Jupyter notebook](https://jupyter.org/), ...).

`$$` allows the user to customise an execution result or provide it asynchronously. For more details, see the documentation: [doc/async.ipynb](http://n-riesco.github.io/ijavascript/doc/async.ipynb.html) and [doc/custom.ipynb](http://n-riesco.github.io/ijavascript/doc/custom.ipynb.html).

`$$` also provides other experimental functionality, like `$$.input()` and `$$.display()`, but I haven't documented them yet.

**Comment by mdjaere** [comment]
Thanks for the explanation!
It makes sense to have variables and keywords available, but I'm not sure it improves the user experience in this case. In JS you'll often use a `;` followed by a line feed, but now, if you're not careful, you'll end up with $$, losing the line feed. Slightly confusing and hinders coding flow IMO.  I am not sure how the system works, but you might want some exclusions/inclusions on what triggers auto-suggestions.

**Comment by n-riesco** [comment]
This is usually handled by the frontend (in your case, I guess, it's [Hydrogen](https://github.com/nteract/hydrogen)).

I've just opened a request on Hydrogen's repo. See https://github.com/nteract/hydrogen/issues/1198 .

**Comment by mdjaere** [comment]
Yep, it's Hydrogen. They sent me here.  Thanks for the update and follow-up.

**Comment by n-riesco** [comment]
@mdjaere Note that this issue isn't specific to IJavascript, the python kernel also shows globals and keywords after `;`. That's the reason I think, it should be handled at frontend level.

**Comment by mdjaere** [comment]
That makes sense, thanks for clearing up. I'll close this now.
