### ISSUE TITLE
Node.js v10 install

### ISSUE THREAD

**Issue by cuiyanbo2019** [n-riesco/ijavascript#177]
Hello,thanks for creating a tool to write notes.I want to use ijavascript to learn javascript. I use win10. but when I install it, it stopped in the libzmq. I don't know whether it can't download the libzmq or it already downloads but can't install. I also find the other way to install libzmq but it seems to be difficult to install libzmq in windows. what should I do now? Thanks for your help.

**Comment by n-riesco** [comment]
If you don't want the hassle of compiling `zeromq.js`, you could use [the previous LTS version of Node.js](https://nodejs.org/dist/latest-v8.x/node-v8.14.0-x64.msi).

Unfortunately, at this time, there are no prebuilt binaries of `zeromq.js` for Node.js v10.

**Comment by Wismin-Effendi** [comment]
installation on win10 won't work since the rebuild of node-gyp.js still using python 2.7 syntax. 

if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax

**Comment by n-riesco** [comment]
@Wismin-Effendi I've opened a new issue to document your problem (see #181).

Closing this issue in favour of #165
