### ISSUE TITLE
How to install IJavascript in anaconda 3

### ISSUE THREAD

**Issue by iduchy** [n-riesco/ijavascript#182]
'npm install -g ijavascript' within conda with python env 3.7 failed:
> gyp ERR! stack Error: Command failed:  ./bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack   File "<string>", line 1
> gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack                                ^
> gyp ERR! stack SyntaxError: invalid syntax

works with python env 2.7

**Comment by n-riesco** [comment]
See #184 for more details on this issue.

Since python v2.7 is only required to build IJavascript's binaries (when the prebuilt binaries aren't available), you should be able to install IJavascript from env 2.7 and use the kernel from any other env.

If you used conda to install Node.js, you may need to install the IJavascript kernelspec using full paths, like this:
```
$ ijsinstall --spec-path=full
```

**Comment by n-riesco** [comment]
Closing in favour of #184

**Comment by iduchy** [comment]
I found the following problem with a hack like working solution:
- conda env uses one defined python version
- to install ijavascript python2.7 required: lets create a new py27 env or install it over py37 (may crash installed dependencies)
- installing jupyterab on py27 gets an old jupyterlab version with nodejs downgrading to v8 (still doesn't work: the kernel has been installed with node v11 and using nodev8 is not a right way today)
- install py37 over py27 within the conda env and install newest jupyterab which runs with node v11
- kernel works fine on newest nodejs, but a new conda environment must be created or installing py27 over existing infrastructure on py37 and then py37 over p27 may crash

**Comment by n-riesco** [comment]
@iduchy I'd need to see the commands you've run and the output you get (and to know the OS you're using).

If I understood correctly, you want to install IJavascript on a py37 conda env (so that you can install and use the latest versions of JupyterLab and Node).

I believe this is possible. The general idea is:

1. activate the py37 env
2. configure npm to use python2: `npm config set python python2`
3. install IJavascript kernelspec: `ijsinstall`

**Comment by iduchy** [comment]
Yes, you understand correctly, but your idea does not work because of conda environment. They say in docs "If you want to use a different version of Python, for example Python 3.5, simply create a new environment and specify the version of Python that you want."

**Comment by n-riesco** [comment]
@iduchy did you try?

Linux and MAC come with their own Python 2 (and in those OSes, you wouldn't need a conda install to run python2)

**Comment by iduchy** [comment]
Thanks, i did not expect conda can see a python installed outside an environment (in /usr/bin)

**Comment by BeyersNel** [comment]
> I believe this is possible. The general idea is:
> 
>     1. activate the py37 env
> 
>     2. configure npm to use python2: `npm config set python python2`
> 
>     3. install IJavascript: `npm install -g ijavascript`
> 
>     4. install IJavascript kernelspec: `ijsinstall --spec-path=full`

This did not resolve the problem for me, instead creating a Python2.7 environment with conda and installing from there worked fine.

**Comment by shytikov** [comment]
Could it be solved by updating `zeromq` to version `5`? The way I have wrote in #201? 

It seems to be roughly 20 issues in this repository on the same topic — and the first one is 2017... It should be possible to resolve them gracefully, without installing second python just for building JS shell.

**Comment by n-riesco** [comment]
@shytikov I've just released `IJavascript@5.2` that uses `jp-kernel@2` and the new prebuilt binaries for `zeromq@5`. This should make life easier for users of Anoconda 3 (at least, for the time being).

**Comment by shytikov** [comment]
@n-riesco everything worked smoothly for me now. And I have pretty strange setup:

* Windows 10 x64;
* Python is installed via Scoop (located in unexpected location);
* Python is version 3.6.8 because of Azure Functions requirement;

But anyhow:

![image](https://user-images.githubusercontent.com/1185905/65755043-9d865c00-e112-11e9-91b3-c3b3817b9924.png)

I believe that solves #181 more or less too.
