### ISSUE TITLE
I can't install the kernel IJavascript  (ijsinstall blocked) Windows 

### ISSUE THREAD

**Issue by Dlyf** [n-riesco/ijavascript#220]
Hello, 

An issue, I can't execute the cmd : ijsinstall

I have : python38, node v12.16.3, npm v6.14.5 
I can run jupyter notebook with : python -m notebook (it's ok) 
I can't execute jupyter notebook 

If i execute the command ijsinstall : 
Error : 
```
C:\Users\domin>ijsinstall
Error running `jupyter --version`
Error: Command failed: jupyter --version
'jupyter' is not recognized as an internal or external command operable program

Error running `ipython --version`
Error: Command failed: ipython --version
'ipython' is not recognized as an internal or external command operable program
```

Thank you

**Comment by Dlyf** [comment]
Sorry, i found ! 
It's OK if we use with the console conda and not cmd windows 
You can closed the issue ;)

**Comment by henrik-jensen** [comment]
Got exactly the same error message.

Think this should be reopened.
It ought to be possible to use cmd (old style cmd.exe terminal) on windows to install and not relying on having an anaconda installation!
What else is the purpose of `c:\Users\<UserName>\AppData\Roaming\npm\ijsinstall.cmd`?

**Comment by n-riesco** [comment]
An anaconda installation is not required, but an installation of `jupyter` is (`ijsinstall` invokes `jupyter` to install its kernelspec).

**Comment by henrik-jensen** [comment]
@n-riesco 
Thanks for the answer.
Ahaha! Well Jupyter must be have been installed somewhere as vscode runs python ipynb's fine.
Actually did get something installed after trying the anaconda install and vscode now also offers the javascript kernel, but it fails running. Should have noted the error messages, but right now I'm in the process of deleting npm cruft made by various apps and reinstalling node js and latest python to get a clean start, so I can't reproduce anything at the moment.
I'll open a new issue if I think it's ijavascript vs vscode related, but the culprit is probably my chaotic windows installation. 😁

**Comment by n-riesco** [comment]
@henrik-jensen 

> Actually did get something installed after trying the anaconda install and vscode now also offers the javascript kernel, but it fails running.

In cases where multiple versions of node.js are present, installing the kernelspec with full paths may help (`ijsinstall --spec-path=full`).

If the node.js version you used to install ijavascript has been removed, you'll have to reinstall ijavascript (so that the zeromq binaries get updated for the current node.js version).

And, if you've installed a kernel spec with full paths, you'll also have to install the kernel spec again (so that it picks up the updated paths).
