### ISSUE TITLE
can I define magics like under IPython ?

### ISSUE THREAD

**Issue by parmentelat** [n-riesco/ijavascript#236]
it's all in the title I guess, I could use the ability to define what IPython supports as `%%mymagic` (my use case is about cell magics)

specifically I'd like to be able to write in one cell some html, css and/or js - with some sort of separators - and embed on the fly a codepen based on that

**Comment by n-riesco** [comment]
I don't support the use of magics because they break Javascript sysntax. In my opinion, they don't belong in a language-agnostic protocol as Jupyter's. See #43 for discussion.

@apowers313 has developed an npm package to support them. See:
* https://www.npmjs.com/package/magicpatch
* https://github.com/n-riesco/ijavascript/issues/43#issuecomment-753674716

Please, continue the discussion n #43.

**Comment by parmentelat** [comment]
thanks for the link to magicpatch which seems to be exactly what I need !
