### ISSUE TITLE
Ijavascript install error

### ISSUE THREAD

**Issue by nilsinhojrx** [n-riesco/ijavascript#238]
Hello, people from github. I got an error when I was trying to install ijavascript kernel in a conda enviroment. 
![error ijavascript](https://user-images.githubusercontent.com/72417934/113496352-35ff5880-94cf-11eb-939b-d63b97180900.png)

**Comment by n-riesco** [comment]
I did notice you were using anaconda in your previous issue (#237). The issue is not about anaconda. The issue is with zeromq not providing prebuilt binaries for recent versions of Node.js. Thus, you need to setup your installation, so that visual studio can build v140 projects. Please, use #221 if you have further enquiries.
