### ISSUE TITLE
IJavaScript stopped working after upgrading the major version of node.js

### ISSUE THREAD

**Issue by Kaiyiccc** [n-riesco/ijavascript#278]
Install failing on macOS Ventura.
Always stalling on the last line.

```
k@MacBook-Pro ~ % npm install -g ijavascript                   
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
(##################) ⠼ reify:zeromq: timing reifyNode:node_modules/ijavascript Completed in 119ms
```

Saw some issues on how zeromq is not caught up with node.js

In that case, what would be the latest version of node.js supported? And which version number is it on npm? Seems like the version number and npm release number are different: [node.js releases](https://nodejs.org/en/download/releases/
)

(I can add the steps to the documentation later)

Thank you!

**Comment by Kaiyiccc** [comment]
somehow rebuilding npm solved my problem... closing the issue

**Comment by n-riesco** [comment]
Thank you for opening this issue.

As you've just discovered, IJavaScript needs reinstalling every time the major version of node.js is upgraded. This is due to one of IJavaScript's dependencies (zeromq) being a binary that requires recompiling to bind against node.js.

I've labelled your issue as a question to help others find about it.
